import { useEffect, useRef, useState } from 'react';

const emptyDocument = { id: '', title: 'Untitled document', content: '', updatedAt: null };
function initials(name = '') { return name.slice(0, 2).toUpperCase(); }
function timeAgo(value) { if (!value) return 'Not saved yet'; const minutes = Math.max(0, Math.round((Date.now() - new Date(value)) / 60000)); return minutes < 1 ? 'Just now' : `${minutes}m ago`; }

function AuthScreen({ onAuth }) {
  const [mode, setMode] = useState('login'); const [form, setForm] = useState({ username: '', email: '', password: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event) { event.preventDefault(); setBusy(true); setError(''); try { const response = await fetch(`/api/auth/${mode}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); onAuth(data.user); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <main className="auth-page"><div className="auth-graphic"><span className="graphic-line line-a" /><span className="graphic-line line-b" /><span className="graphic-dot dot-a" /><span className="graphic-dot dot-b" /><span className="graphic-note">A shared place for clear thinking</span></div><section className="auth-card"><div className="brand"><span className="brand-mark"><i /><i /><i /></span><strong>SIGNAL</strong></div><p className="eyebrow">Real-time writing studio</p><h1>Ideas get better<br /><em>when they move.</em></h1><p className="auth-copy">Write, shape, and refine documents with your team in one living workspace.</p><form onSubmit={submit}>{mode === 'register' && <input placeholder="Username" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} required />}{mode === 'register' && <small>3-24 letters, numbers, underscores, or hyphens</small>}<input type="email" placeholder="Email address" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /><input type="password" placeholder="Password" minLength="8" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required />{error && <p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy ? 'Opening workspace...' : mode === 'login' ? 'Enter workspace' : 'Create account'} <span>↗</span></button></form><button className="switch" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError(''); }}>{mode === 'login' ? 'New here? Create an account' : 'Already have an account? Sign in'}</button></section></main>;
}

function App({ socket }) {
  const [user, setUser] = useState(null); const [documents, setDocuments] = useState([]); const [document, setDocument] = useState(emptyDocument); const [members, setMembers] = useState([]); const [status, setStatus] = useState('Synced'); const editorRef = useRef(null); const saveTimer = useRef(null);
  async function openDocument(id) { const response = await fetch(`/api/documents/${id}`); if (!response.ok) return; const data = await response.json(); setDocument(data.document); if (editorRef.current) editorRef.current.innerHTML = data.document.content || '<p><br></p>'; socket.emit('open-document', id); window.history.replaceState({}, '', `?document=${id}`); }
  async function createDocument() { const response = await fetch('/api/documents', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: 'Untitled document' }) }); const data = await response.json(); setDocuments((items) => [data.document, ...items]); openDocument(data.document.id); }
  async function loadWorkspace(currentUser) { setUser(currentUser); const response = await fetch('/api/documents'); const data = await response.json(); setDocuments(data.documents); const sharedId = new URLSearchParams(window.location.search).get('document'); if (sharedId) openDocument(sharedId); else if (data.documents[0]) openDocument(data.documents[0].id); else createDocument(); socket.connect(); }
  function scheduleSave(nextTitle = document.title) { setStatus('Saving'); clearTimeout(saveTimer.current); saveTimer.current = setTimeout(() => socket.emit('edit-document', { documentId: document.id, title: nextTitle, content: editorRef.current?.innerHTML || '' }), 350); }
  function updateTitle(title) { setDocument((current) => ({ ...current, title })); scheduleSave(title); }
  function updateEditor() { scheduleSave(); }
  async function share() { const link = `${location.origin}${location.pathname}?document=${document.id}`; try { await navigator.clipboard.writeText(link); setStatus('Link copied'); setTimeout(() => setStatus('Synced'), 2000); } catch { window.prompt('Copy document link', link); } }
  async function logout() { await fetch('/api/auth/logout', { method: 'POST' }); socket.disconnect(); setUser(null); }
  useEffect(() => { fetch('/api/auth/me').then((r) => r.ok ? r.json() : Promise.reject()).then(({ user: currentUser }) => loadWorkspace(currentUser)).catch(() => {}); const loaded = (item) => { setDocument(item); requestAnimationFrame(() => { if (editorRef.current) editorRef.current.innerHTML = item.content || '<p><br></p>'; }); }; const updated = (item) => { setDocument((current) => ({ ...current, ...item })); if (editorRef.current && editorRef.current.innerHTML !== item.content) editorRef.current.innerHTML = item.content; setStatus('Synced'); }; const saved = ({ updatedAt }) => { setDocument((current) => ({ ...current, updatedAt })); setStatus('Synced'); }; socket.on('document-loaded', loaded); socket.on('document-updated', updated); socket.on('document-saved', saved); socket.on('presence-updated', setMembers); return () => { clearTimeout(saveTimer.current); socket.off('document-loaded', loaded); socket.off('document-updated', updated); socket.off('document-saved', saved); socket.off('presence-updated', setMembers); }; }, []);
  if (!user) return <AuthScreen onAuth={loadWorkspace} />;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><i /><i /><i /></span><strong>SIGNAL</strong></div><div className="workspace"><span>Workspace</span><strong>Fieldwork</strong></div><div className="section-heading"><span>Documents</span><button onClick={createDocument} aria-label="Create document">+</button></div><div className="documents">{documents.map((item) => <button className={`document ${item.id === document.id ? 'active' : ''}`} key={item.id} onClick={() => openDocument(item.id)}><span className="document-icon">◒</span><span><strong>{item.title}</strong><small>{timeAgo(item.updatedAt)}</small></span></button>)}</div><div className="account"><div className="avatar" style={{ background: user.color }}>{initials(user.username)}</div><span><strong>{user.username}</strong><small>{user.email}</small></span><button onClick={logout} aria-label="Sign out">↗</button></div></aside><main className="main"><header className="topbar"><div className="crumb"><span>Fieldwork</span><b>/</b><strong>{document.title}</strong></div><div className="top-actions"><span className={status === 'Saving' ? 'saving' : ''}><i />{status}</span><button onClick={share}>Share ↗</button></div></header><div className="toolbar"><button onClick={() => document.execCommand('bold')}><b>B</b></button><button onClick={() => document.execCommand('italic')}><i>I</i></button><button onClick={() => document.execCommand('underline')}><u>U</u></button><span /><button onClick={() => document.execCommand('insertUnorderedList')}>☷</button><button onClick={() => document.execCommand('formatBlock', false, 'blockquote')}>❝</button></div><section className="paper"><div className="paper-heading"><input value={document.title} onChange={(e) => updateTitle(e.target.value)} aria-label="Document title" /><p>{timeAgo(document.updatedAt)} <span>·</span> Live document</p></div><div className="editor" ref={editorRef} contentEditable suppressContentEditableWarning onInput={updateEditor} data-placeholder="Start writing something worth sharing..." /></section></main><aside className="people"><div className="people-title"><span>Collaborators</span><strong>{members.length || 1} online</strong></div>{members.map((member) => <div className="person" key={`${member.id}-${member.username}`}><div className="avatar" style={{ background: member.color }}>{initials(member.username)}</div><span><strong>{member.username}{member.username === user.username ? ' (you)' : ''}</strong><small><i /> Editing now</small></span></div>)}<div className="live-note"><strong>Live collaboration</strong><p>Share this document to invite a teammate. Every change is saved as you write.</p></div></aside></div>;
}

export default App;
